import { Category, Job } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "1", name: "Engineering", icon: "💻", jobCount: 2340 },
  { id: "2", name: "Marketing", icon: "📊", jobCount: 870 },
  { id: "3", name: "Design", icon: "🎨", jobCount: 640 },
  { id: "4", name: "Finance", icon: "💰", jobCount: 1120 },
  { id: "5", name: "Healthcare", icon: "🧑‍⚕️", jobCount: 560 },
  { id: "6", name: "Operations", icon: "📦", jobCount: 430 },
  { id: "7", name: "Sales", icon: "🤝", jobCount: 720 },
  { id: "8", name: "HR", icon: "👥", jobCount: 310 },
];

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    description: "We are looking for an experienced frontend developer...",
    location: "Dhaka, Bangladesh",
    salaryMin: 80000,
    salaryMax: 120000,
    category: "Engineering",
    jobType: "Full-time",
    workMode: "Remote",
    employerId: "emp1",
    companyName: "Bkash Limited",
    tags: ["React", "TypeScript", "Next.js"],
    featured: true,
    postedAt: "2025-04-13",
  },
  {
    id: "2",
    title: "Product Designer (UX/UI)",
    description: "Join our design team to craft beautiful user experiences...",
    location: "Chittagong",
    salaryMin: 55000,
    salaryMax: 75000,
    category: "Design",
    jobType: "Full-time",
    workMode: "Hybrid",
    employerId: "emp2",
    companyName: "Shohoz Technologies",
    tags: ["Figma", "Mobile", "Research"],
    featured: false,
    postedAt: "2025-04-14",
  },
  {
    id: "3",
    title: "Backend Engineer (Node.js)",
    description: "Build scalable APIs and microservices for our platform...",
    location: "Remote",
    salaryMin: 60000,
    salaryMax: 90000,
    category: "Engineering",
    jobType: "Part-time",
    workMode: "Remote",
    employerId: "emp3",
    companyName: "Pathao Courier",
    tags: ["Node.js", "PostgreSQL", "Docker"],
    featured: false,
    postedAt: "2025-04-12",
  },
  {
    id: "4",
    title: "Digital Marketing Manager",
    description: "Lead our digital marketing strategy and team...",
    location: "Dhaka",
    salaryMin: 50000,
    salaryMax: 70000,
    category: "Marketing",
    jobType: "Full-time",
    workMode: "Onsite",
    employerId: "emp4",
    companyName: "Daraz Bangladesh",
    tags: ["SEO", "Analytics", "Social Media"],
    featured: false,
    postedAt: "2025-04-10",
  },
  {
    id: "5",
    title: "Data Scientist",
    description: "Analyze complex data and build ML models...",
    location: "Dhaka",
    salaryMin: 100000,
    salaryMax: 150000,
    category: "Engineering",
    jobType: "Full-time",
    workMode: "Hybrid",
    employerId: "emp5",
    companyName: "Robi Axiata",
    tags: ["Python", "ML", "TensorFlow"],
    featured: true,
    postedAt: "2025-04-15",
  },
  {
    id: "6",
    title: "DevOps Engineer",
    description: "Manage our cloud infrastructure and CI/CD pipelines...",
    location: "Remote",
    salaryMin: 90000,
    salaryMax: 130000,
    category: "Engineering",
    jobType: "Full-time",
    workMode: "Remote",
    employerId: "emp6",
    companyName: "Grameenphone IT",
    tags: ["AWS", "Docker", "Kubernetes"],
    featured: false,
    postedAt: "2025-04-11",
  },
];

export const JOB_FILTER_TABS = [
  "All",
  "Remote",
  "Full-time",
  "Part-time",
  "Senior",
  "Entry Level",
];

export const LOCATIONS = [
  "All Locations",
  "Dhaka",
  "Chittagong",
  "Sylhet",
  "Rajshahi",
  "Remote",
];

export const STATS = [
  { value: "12,400+", label: "Active Jobs" },
  { value: "3,200+", label: "Companies" },
  { value: "98k+", label: "Job Seekers" },
];
